module.exports = {
  GITHUB_API_KEY: 'FILL_ME_IN',
  GOOGLE_SHEETS_API_KEY: 'FILL_ME_IN',
  GOOGLE_GROUPS_API_KEY: 'FILL_ME_IN',
  GOOGLE_MAIL_API_KEY: 'FILL_ME_IN',
  LEARN_API_KEY: 'FILL_ME_IN',
  SALESFORCE_API_KEY: 'FILL_ME_IN',
  SLACK_API_KEY: 'FILL_ME_IN',
  ETC: 'FILL_ME_IN',
};
